feat : added a new profile page to help teachers create their profile.
freeCodeCamp/classroom pull request #254
Opened 2023-02-23 00:31 UTC by PrajwalPisal

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #2

Description:

This pull request adds a new feature to the project: a teacher profile page where teachers can create and edit their profile information. The page is built using Next.js and uses the localStorage API to store user data as a JSON object, ensuring that the user's data will persist even after the user closes the browser or navigates away from the page.

On the profile page, teachers can input their name, email, university, and a short bio. The page is designed to be user-friendly and easy to navigate. The information is not yet stored in a database, but the use of localStorage provides a temporary solution until further development is done.

2023-02-27 16:43 UTC, roberthuskins commented
@PrajwalPisal can you add some pictures to the PR for future reference? 
Also if you want to merge this pull request I would recommend not linking this page anywhere else in the app since as you mentioned saving the user's profile to localstorage is temporary. When it's 100% complete we can link it.

You can add some fields to the Prisma Schema no problem to help you with the DB, just make a separate PR for us.

2023-02-27 16:45 UTC, roberthuskins requested changes

2023-02-27 16:45 UTC, roberthuskins commented on pages/profile.js
> +                <img
use next/image as pointed out by codefactor

2023-08-03 23:34 UTC, GuillermoFloresV commented
Closed due to inactivity. 

If you would still like to contribute, please resubmit this PR with the appropriate changes mentioned by Robert. 

Thanks!

2023-08-03 23:34 UTC, closed without merging