feat: add ci pipeline
freeCodeCamp/classroom pull request #348
Opened 2023-07-03 14:16 UTC by Ismailtlem

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Related to #150

2023-07-03 14:22 UTC, Ismailtlem commented
Hi @GuillermoFloresV , @utsab

Can you have a look ?

2023-07-09 20:52 UTC, GuillermoFloresV requested changes

2023-07-09 20:52 UTC, GuillermoFloresV commented on next.config.js
> +
Can we get rid of this extra space here?

2023-07-09 20:54 UTC, GuillermoFloresV approved these changes

2023-07-09 20:54 UTC, GuillermoFloresV commented
Fixed a quick nit (extra space in `next.config`) to eliminate the need for a back and forth, thanks @Ismailtlem !

2023-07-09 20:55 UTC, merged